import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from 'next-themes'
import Navbar from "@/src/components/ui/Navbar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "100",
  style: "italic"
});


export const metadata: Metadata = {
  title: " Alain tanguy ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">

      <body
        className={`${poppins.variable} antialiased m-0 p-0  box-border  dark:bg-third dark:text-second  bg-second text-third  `}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Navbar />
          <div className="">
            {children}
          </div>
        </ThemeProvider>
      </body>


    </html>
  );
}
